app = "arka-code"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[http_service.ports]]
  port = 80

[[http_service.ports]]
  port = 443
  handlers = ["tls"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"  # MySQL necesita más memoria